"""Shared constants. There is deliberately no broker order vocabulary here."""

DATA_UNAVAILABLE = "DATA UNAVAILABLE"
MANUAL_ONLY = "MANUAL REVIEW / MANUAL SUBMISSION ONLY"
RESEARCH_ONLY = "RESEARCH_ONLY"
SCHEMA_VERSION = "corat.run.v2"

TARGET_TRADE = "TARGET TRADE"
SETUP_ONLY = "SETUP ONLY — NOT A TRADE"
NO_POSITIVE_EDGE = "NO TRADE — EDGE NOT POSITIVE"
WATCHLIST = "WATCHLIST"
REJECTED = "REJECTED / AVOID"

# Legacy names remain importable for old ledger rows and old immutable runs.
ACTIONABLE_NOW = "ACTIONABLE NOW"
WAIT_FOR_TRIGGER = "WAIT FOR TRIGGER"

VALID_STATUSES = (TARGET_TRADE, SETUP_ONLY, NO_POSITIVE_EDGE, WATCHLIST, REJECTED)
